application: {{ APPLICATION_ID }}
version: 1-2-5
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "10m"
instance_class: F1

automatic_scaling:
    min_idle_instances: automatic
    max_idle_instances: automatic
    min_pending_latency: automatic
    max_pending_latency: automatic

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*/dev$

builtins:
- appstats: on
- remote_api: on
- deferred: on

handlers:
- url: /robots\.txt
  static_files: robots.txt
  upload: robots.txt
  secure: optional

- url: /humans\.txt
  static_files: humans.txt
  upload: humans.txt
  secure: optional

- url: /assets
  static_dir: dist/assets
  secure: always

- url: /files
  static_dir: dist/files
  secure: always

- url: /exhibitor(/?)
  static_files: dist/files/exhibitor.pdf
  upload: dist/files/exhibitor.pdf
  secure: always

- url: /sponsor(s?)(/?)
  static_files: dist/files/sponsorship.pdf
  upload: dist/files/sponsorship.pdf
  secure: always

- url: /rules(/?)
  static_files: dist/files/rules.pdf
  upload: dist/files/rules.pdf
  secure: always

- url: /opensource(/?)
  static_files: dist/files/opensource.pdf
  upload: dist/files/opensource.pdf
  secure: always

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin
  secure: optional

- url: .*
  script: main.app
  secure: always

libraries:
- name: ssl
  version: latest

- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "2.6"

env_variables:
  ADMIN_ID: {{ ADMIN_ID }}
  MAILGUN_SECRET: {{ MAILGUN_SECRET }}
  HARDWARE_SECRET: {{ HARDWARE_SECRET }}
  IS_DEVELOPMENT: {{ IS_DEVELOPMENT }}
